export default {
  API_URI: '',
  API_KEY: '',
  API_IMG: '',
  MAP_API_KEY: '',

  SIZE_MATTERS_BASE_WIDTH: null,
  SIZE_MATTERS_BASE_HEIGHT: null,

  INPUT_HEIGHT: null,
  HEADER_HEIGHT: null,

  // TIMERS
  HIDDEN_KEYBOARD_TIME: 200,
  OPEN_KEYBOARD_TIME: 600,
  ASYNC_CALLBACK_TIME: 300,
  POPUP_TIME: 2000,

  RESEND_CODE_TIMER: 1000,
  RESEND_CODE_REMINDER_TIME: 10,
  RESEND_CODE_CAN_RESEND_TIME: 60,

  DEBOUNCE_TIME: 1000,
  NAVIGATION_MODAL_TIME: 400,
};
